name: Build master docker images for integration tests
on:
  push:
    branches:
      - master
jobs:
  docker_build:
    strategy:
      fail-fast: false
      matrix:
        tag: [ 'master', 'master_debug' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Extract metadata from Github
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fluentbitdev/fluent-bit
          tags: |
            raw,x86_64-master-${{ matrix.tag }}

      - name: Build the staging image
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfiles/Dockerfile.x86_64-master
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
          load: false
