name: Run integration tests for PR
on:
  pull_request_target:
    branches:
      - master
    types:
      - labeled
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  publish-docker-images:
    name: publish the docker images for PR
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    runs-on: ubuntu-latest
    steps:
      - name: Wait for docker build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: docker_build
          timeoutSeconds: 3600
          intervalSeconds: 10
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait until artifacts are propagated
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'

      - name: Download docker image from build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: integration-build-pr.yaml
          pr: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
          name: action_image_artifact_${{ env.dockerhub_organization }}_fluent-bit_${{ env.arch }}-master-pr-${{ env.pr }}
          path: images
        env:
          pr: ${{github.event.pull_request.number}}
          arch: x86_64
          dockerhub_organization: fluentbitdev

      - name: Import docker image
        run: |
          docker load --input ./images/${{ env.dockerhub_organization }}_fluent-bit_${{ env.arch }}-master-pr-${{ env.pr }}
        env:
          pr: ${{github.event.pull_request.number}}
          arch: x86_64
          dockerhub_organization: fluentbitdev

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker push ${{ env.dockerhub_organization }}/fluent-bit:${{ env.arch }}-master-pr-${{ env.pr }}
        env:
          pr: ${{ github.event.number }}
          arch: x86_64
          dockerhub_organization: fluentbitdev

      - uses: actions-ecosystem/action-add-labels@v1
        name: Label the PR
        with:
          labels: ci/integration-docker-ok
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          repo: fluent/fluent-bit

  run-integration-gcp:
    needs: publish-docker-images
    uses: calyptia/fluent-bit-ci/.github/workflows/reusable-integration-test-gcp.yaml@main
    with:
      image_name: fluentbitdev/fluent-bit
      image_tag: x86_64-master-pr-${{ github.event.pull_request.number }}
    secrets:
      grafana_username: ${{ secrets.GRAFANA_USERNAME }}
      terraform_api_token: ${{ secrets.TF_API_TOKEN }}
      gcp_service_account_key: ${{ secrets.GCP_SA_KEY }}
      grafana_password: ${{ secrets.GRAFANA_PASSWORD }}

  run-integration-post-label:
    runs-on: ubuntu-latest
    needs: run-integration-gcp
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        name: Label the PR
        with:
          labels: ci/integration-test-gcp-ok
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          repo: fluent/fluent-bit
